name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [3.0, 2.7, 2.6]
    steps:
    - name: Install libdnssd
      run: sudo apt-get install libavahi-compat-libdnssd-dev
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Install dependencies
      run: bundle
    - name: Run tests
      run: bundle exec rake
  mac:
    runs-on: macos-latest
    strategy:
      matrix:
        ruby-version: [3.0, 2.7, 2.6]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Install dependencies
      run: bundle
    - name: Run tests
      run: bundle exec rake
